apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-chaoslog
  namespace: default
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: chaos-log-app
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "45s"
