# 1. Entrada Forward (Para a API e Worker usarem o driver nativo do Docker)
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

# 2. Entrada Syslog (Para o Logspout capturar tudo automaticamente)
<source>
  @type syslog
  port 5140
  bind 0.0.0.0
  tag docker.syslog
  <parse>
    @type none
  </parse>
</source>

# 3. Entrada HTTP (Para você mandar logs via 'curl' ou scripts de teste)
<source>
  @type http
  port 8888
  bind 0.0.0.0
</source>

# FILTRO: Adiciona o nome do container se vier do syslog
<filter docker.syslog.**>
  @type record_transformer
  <record>
    service_name "logspout-capture"
  </record>
</filter>

<match docker.**>
  @type file
  path /fluentd/log/docker-logs
  append true
  <buffer>
    @type memory      # Grava o buffer na memória para ser mais rápido
    flush_mode interval
    flush_interval 1s # Escreve no arquivo a cada 1 segundo
  </buffer>
</match>
